//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanBangTotNghiep_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_ChuyenNganh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dm_ChuyenNganh()
        {
            this.dm_SinhVien = new HashSet<dm_SinhVien>();
        }
    
        public int Id_ChuyenNganh { get; set; }
        public string Ma_ChuyenNganh { get; set; }
        public string Ten_ChuyenNganh { get; set; }
        public Nullable<int> Id_NganhHoc { get; set; }
        public bool Trang_Thai_Su_Dung { get; set; }
    
        public virtual dm_NganhHoc dm_NganhHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dm_SinhVien> dm_SinhVien { get; set; }
    }
}
