//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanBangTotNghiep_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_KhoaHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dm_KhoaHoc()
        {
            this.dm_SinhVien = new HashSet<dm_SinhVien>();
        }
    
        public int Id_KhoaHoc { get; set; }
        public string Ma_KhoaHoc { get; set; }
        public Nullable<int> Nam_Bat_Dau { get; set; }
        public Nullable<int> Nam_Ket_Thuc { get; set; }
        public bool Trang_Thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dm_SinhVien> dm_SinhVien { get; set; }
    }
}
