//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanBangTotNghiep_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_NganhHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dm_NganhHoc()
        {
            this.dm_ChuyenNganh = new HashSet<dm_ChuyenNganh>();
        }
    
        public int Id_NganhHoc { get; set; }
        public string Ma_NganhHoc { get; set; }
        public string Ten_Nganh { get; set; }
        public bool Trang_Thai_Su_Dung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dm_ChuyenNganh> dm_ChuyenNganh { get; set; }
    }
}
