//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanBangTotNghiep_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_PhanQuyenNguoiDung
    {
        public int Id_LoaiNguoiDung { get; set; }
        public string Ma_LoaiNguoiDung { get; set; }
        public string Ten_LoaiNguoiDung { get; set; }
        public bool Trang_Thai_Su_Dung { get; set; }
    }
}
