//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanBangTotNghiep_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoiBang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhoiBang()
        {
            this.VanBangChinhThucs = new HashSet<VanBangChinhThuc>();
        }
    
        public int Id_PhoiBang { get; set; }
        public string SoHieuPhoi { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public int TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VanBangChinhThuc> VanBangChinhThucs { get; set; }
    }
}
