//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanBangTotNghiep_BTL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLVB_Entities : DbContext
    {
        public QLVB_Entities()
            : base("name=QLVB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dm_ChuyenNganh> dm_ChuyenNganh { get; set; }
        public virtual DbSet<dm_DonViQuanLy> dm_DonViQuanLy { get; set; }
        public virtual DbSet<dm_KhoaHoc> dm_KhoaHoc { get; set; }
        public virtual DbSet<dm_NganhHoc> dm_NganhHoc { get; set; }
        public virtual DbSet<dm_NguoiDung> dm_NguoiDung { get; set; }
        public virtual DbSet<dm_PhanQuyenNguoiDung> dm_PhanQuyenNguoiDung { get; set; }
        public virtual DbSet<dm_SinhVien> dm_SinhVien { get; set; }
        public virtual DbSet<dm_XepLoai> dm_XepLoai { get; set; }
        public virtual DbSet<DotCapBangTN> DotCapBangTNs { get; set; }
        public virtual DbSet<VanBangTN> VanBangTNs { get; set; }
    
        public virtual ObjectResult<chon_chuyennganh_Result> chon_chuyennganh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<chon_chuyennganh_Result>("chon_chuyennganh");
        }
    
        public virtual ObjectResult<chon_donviquanly_Result> chon_donviquanly()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<chon_donviquanly_Result>("chon_donviquanly");
        }
    
        public virtual ObjectResult<chon_dot_cap_Result> chon_dot_cap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<chon_dot_cap_Result>("chon_dot_cap");
        }
    
        public virtual ObjectResult<chon_khoahoc_Result> chon_khoahoc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<chon_khoahoc_Result>("chon_khoahoc");
        }
    
        public virtual ObjectResult<chon_nganhhoc_Result> chon_nganhhoc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<chon_nganhhoc_Result>("chon_nganhhoc");
        }
    
        public virtual ObjectResult<chon_nguoidung_Result> chon_nguoidung()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<chon_nguoidung_Result>("chon_nguoidung");
        }
    
        public virtual ObjectResult<chon_xeploai_Result> chon_xeploai()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<chon_xeploai_Result>("chon_xeploai");
        }
    
        public virtual int sua_chuyennganh(Nullable<int> id_ChuyenNganh, string ma_ChuyenNganh, string ten_ChuyenNganh, Nullable<int> id_NganhHoc, Nullable<bool> trang_Thai_Su_Dung)
        {
            var id_ChuyenNganhParameter = id_ChuyenNganh.HasValue ?
                new ObjectParameter("Id_ChuyenNganh", id_ChuyenNganh) :
                new ObjectParameter("Id_ChuyenNganh", typeof(int));
    
            var ma_ChuyenNganhParameter = ma_ChuyenNganh != null ?
                new ObjectParameter("Ma_ChuyenNganh", ma_ChuyenNganh) :
                new ObjectParameter("Ma_ChuyenNganh", typeof(string));
    
            var ten_ChuyenNganhParameter = ten_ChuyenNganh != null ?
                new ObjectParameter("Ten_ChuyenNganh", ten_ChuyenNganh) :
                new ObjectParameter("Ten_ChuyenNganh", typeof(string));
    
            var id_NganhHocParameter = id_NganhHoc.HasValue ?
                new ObjectParameter("Id_NganhHoc", id_NganhHoc) :
                new ObjectParameter("Id_NganhHoc", typeof(int));
    
            var trang_Thai_Su_DungParameter = trang_Thai_Su_Dung.HasValue ?
                new ObjectParameter("Trang_Thai_Su_Dung", trang_Thai_Su_Dung) :
                new ObjectParameter("Trang_Thai_Su_Dung", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_chuyennganh", id_ChuyenNganhParameter, ma_ChuyenNganhParameter, ten_ChuyenNganhParameter, id_NganhHocParameter, trang_Thai_Su_DungParameter);
        }
    
        public virtual int sua_donviquanly(Nullable<int> id_DonViQuanLy, string ma_DonViQuanLy, string ten_DonViQuanLy, string ten_DonViQuanLy_Cha, Nullable<bool> trang_Thai_Su_Dung)
        {
            var id_DonViQuanLyParameter = id_DonViQuanLy.HasValue ?
                new ObjectParameter("Id_DonViQuanLy", id_DonViQuanLy) :
                new ObjectParameter("Id_DonViQuanLy", typeof(int));
    
            var ma_DonViQuanLyParameter = ma_DonViQuanLy != null ?
                new ObjectParameter("Ma_DonViQuanLy", ma_DonViQuanLy) :
                new ObjectParameter("Ma_DonViQuanLy", typeof(string));
    
            var ten_DonViQuanLyParameter = ten_DonViQuanLy != null ?
                new ObjectParameter("Ten_DonViQuanLy", ten_DonViQuanLy) :
                new ObjectParameter("Ten_DonViQuanLy", typeof(string));
    
            var ten_DonViQuanLy_ChaParameter = ten_DonViQuanLy_Cha != null ?
                new ObjectParameter("Ten_DonViQuanLy_Cha", ten_DonViQuanLy_Cha) :
                new ObjectParameter("Ten_DonViQuanLy_Cha", typeof(string));
    
            var trang_Thai_Su_DungParameter = trang_Thai_Su_Dung.HasValue ?
                new ObjectParameter("Trang_Thai_Su_Dung", trang_Thai_Su_Dung) :
                new ObjectParameter("Trang_Thai_Su_Dung", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_donviquanly", id_DonViQuanLyParameter, ma_DonViQuanLyParameter, ten_DonViQuanLyParameter, ten_DonViQuanLy_ChaParameter, trang_Thai_Su_DungParameter);
        }
    
        public virtual int sua_dot_cap(Nullable<int> id_Dot_Cap, string ten_Van_Bang, string ten_Dot_Cap)
        {
            var id_Dot_CapParameter = id_Dot_Cap.HasValue ?
                new ObjectParameter("Id_Dot_Cap", id_Dot_Cap) :
                new ObjectParameter("Id_Dot_Cap", typeof(int));
    
            var ten_Van_BangParameter = ten_Van_Bang != null ?
                new ObjectParameter("Ten_Van_Bang", ten_Van_Bang) :
                new ObjectParameter("Ten_Van_Bang", typeof(string));
    
            var ten_Dot_CapParameter = ten_Dot_Cap != null ?
                new ObjectParameter("Ten_Dot_Cap", ten_Dot_Cap) :
                new ObjectParameter("Ten_Dot_Cap", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_dot_cap", id_Dot_CapParameter, ten_Van_BangParameter, ten_Dot_CapParameter);
        }
    
        public virtual int sua_khoahoc(Nullable<int> id_KhoaHoc, string ma_KhoaHoc, Nullable<int> nam_Bat_Dau, Nullable<int> nam_Ket_Thuc, Nullable<bool> trang_Thai)
        {
            var id_KhoaHocParameter = id_KhoaHoc.HasValue ?
                new ObjectParameter("Id_KhoaHoc", id_KhoaHoc) :
                new ObjectParameter("Id_KhoaHoc", typeof(int));
    
            var ma_KhoaHocParameter = ma_KhoaHoc != null ?
                new ObjectParameter("Ma_KhoaHoc", ma_KhoaHoc) :
                new ObjectParameter("Ma_KhoaHoc", typeof(string));
    
            var nam_Bat_DauParameter = nam_Bat_Dau.HasValue ?
                new ObjectParameter("Nam_Bat_Dau", nam_Bat_Dau) :
                new ObjectParameter("Nam_Bat_Dau", typeof(int));
    
            var nam_Ket_ThucParameter = nam_Ket_Thuc.HasValue ?
                new ObjectParameter("Nam_Ket_Thuc", nam_Ket_Thuc) :
                new ObjectParameter("Nam_Ket_Thuc", typeof(int));
    
            var trang_ThaiParameter = trang_Thai.HasValue ?
                new ObjectParameter("Trang_Thai", trang_Thai) :
                new ObjectParameter("Trang_Thai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_khoahoc", id_KhoaHocParameter, ma_KhoaHocParameter, nam_Bat_DauParameter, nam_Ket_ThucParameter, trang_ThaiParameter);
        }
    
        public virtual int sua_nganhhoc(Nullable<int> id_NganhHoc, string ma_NganhHoc, string ten_Nganh, Nullable<bool> trang_Thai_Su_Dung)
        {
            var id_NganhHocParameter = id_NganhHoc.HasValue ?
                new ObjectParameter("Id_NganhHoc", id_NganhHoc) :
                new ObjectParameter("Id_NganhHoc", typeof(int));
    
            var ma_NganhHocParameter = ma_NganhHoc != null ?
                new ObjectParameter("Ma_NganhHoc", ma_NganhHoc) :
                new ObjectParameter("Ma_NganhHoc", typeof(string));
    
            var ten_NganhParameter = ten_Nganh != null ?
                new ObjectParameter("Ten_Nganh", ten_Nganh) :
                new ObjectParameter("Ten_Nganh", typeof(string));
    
            var trang_Thai_Su_DungParameter = trang_Thai_Su_Dung.HasValue ?
                new ObjectParameter("Trang_Thai_Su_Dung", trang_Thai_Su_Dung) :
                new ObjectParameter("Trang_Thai_Su_Dung", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_nganhhoc", id_NganhHocParameter, ma_NganhHocParameter, ten_NganhParameter, trang_Thai_Su_DungParameter);
        }
    
        public virtual int sua_nguoidung(Nullable<int> id_NguoiDung, string ma_NguoiDung, string ten_Dang_Nhap, string mat_Khau, string loai_NguoiDung)
        {
            var id_NguoiDungParameter = id_NguoiDung.HasValue ?
                new ObjectParameter("Id_NguoiDung", id_NguoiDung) :
                new ObjectParameter("Id_NguoiDung", typeof(int));
    
            var ma_NguoiDungParameter = ma_NguoiDung != null ?
                new ObjectParameter("Ma_NguoiDung", ma_NguoiDung) :
                new ObjectParameter("Ma_NguoiDung", typeof(string));
    
            var ten_Dang_NhapParameter = ten_Dang_Nhap != null ?
                new ObjectParameter("Ten_Dang_Nhap", ten_Dang_Nhap) :
                new ObjectParameter("Ten_Dang_Nhap", typeof(string));
    
            var mat_KhauParameter = mat_Khau != null ?
                new ObjectParameter("Mat_Khau", mat_Khau) :
                new ObjectParameter("Mat_Khau", typeof(string));
    
            var loai_NguoiDungParameter = loai_NguoiDung != null ?
                new ObjectParameter("Loai_NguoiDung", loai_NguoiDung) :
                new ObjectParameter("Loai_NguoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_nguoidung", id_NguoiDungParameter, ma_NguoiDungParameter, ten_Dang_NhapParameter, mat_KhauParameter, loai_NguoiDungParameter);
        }
    
        public virtual int sua_sinhvien(Nullable<int> id_SinhVien, string ma_SinhVien, string ho_Va_Ten, Nullable<bool> gioi_Tinh, Nullable<System.DateTime> ngay_Sinh, Nullable<int> id_ChuyenNganh, Nullable<int> id_KhoaHoc, string so_Dien_Thoai, string email, Nullable<decimal> diem_Trung_Binh_Tich_Luy, Nullable<int> id_XepLoai, Nullable<int> id_DonViQuanLy, Nullable<bool> trang_Thai)
        {
            var id_SinhVienParameter = id_SinhVien.HasValue ?
                new ObjectParameter("Id_SinhVien", id_SinhVien) :
                new ObjectParameter("Id_SinhVien", typeof(int));
    
            var ma_SinhVienParameter = ma_SinhVien != null ?
                new ObjectParameter("Ma_SinhVien", ma_SinhVien) :
                new ObjectParameter("Ma_SinhVien", typeof(string));
    
            var ho_Va_TenParameter = ho_Va_Ten != null ?
                new ObjectParameter("Ho_Va_Ten", ho_Va_Ten) :
                new ObjectParameter("Ho_Va_Ten", typeof(string));
    
            var gioi_TinhParameter = gioi_Tinh.HasValue ?
                new ObjectParameter("Gioi_Tinh", gioi_Tinh) :
                new ObjectParameter("Gioi_Tinh", typeof(bool));
    
            var ngay_SinhParameter = ngay_Sinh.HasValue ?
                new ObjectParameter("Ngay_Sinh", ngay_Sinh) :
                new ObjectParameter("Ngay_Sinh", typeof(System.DateTime));
    
            var id_ChuyenNganhParameter = id_ChuyenNganh.HasValue ?
                new ObjectParameter("Id_ChuyenNganh", id_ChuyenNganh) :
                new ObjectParameter("Id_ChuyenNganh", typeof(int));
    
            var id_KhoaHocParameter = id_KhoaHoc.HasValue ?
                new ObjectParameter("Id_KhoaHoc", id_KhoaHoc) :
                new ObjectParameter("Id_KhoaHoc", typeof(int));
    
            var so_Dien_ThoaiParameter = so_Dien_Thoai != null ?
                new ObjectParameter("So_Dien_Thoai", so_Dien_Thoai) :
                new ObjectParameter("So_Dien_Thoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var diem_Trung_Binh_Tich_LuyParameter = diem_Trung_Binh_Tich_Luy.HasValue ?
                new ObjectParameter("Diem_Trung_Binh_Tich_Luy", diem_Trung_Binh_Tich_Luy) :
                new ObjectParameter("Diem_Trung_Binh_Tich_Luy", typeof(decimal));
    
            var id_XepLoaiParameter = id_XepLoai.HasValue ?
                new ObjectParameter("Id_XepLoai", id_XepLoai) :
                new ObjectParameter("Id_XepLoai", typeof(int));
    
            var id_DonViQuanLyParameter = id_DonViQuanLy.HasValue ?
                new ObjectParameter("Id_DonViQuanLy", id_DonViQuanLy) :
                new ObjectParameter("Id_DonViQuanLy", typeof(int));
    
            var trang_ThaiParameter = trang_Thai.HasValue ?
                new ObjectParameter("Trang_Thai", trang_Thai) :
                new ObjectParameter("Trang_Thai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_sinhvien", id_SinhVienParameter, ma_SinhVienParameter, ho_Va_TenParameter, gioi_TinhParameter, ngay_SinhParameter, id_ChuyenNganhParameter, id_KhoaHocParameter, so_Dien_ThoaiParameter, emailParameter, diem_Trung_Binh_Tich_LuyParameter, id_XepLoaiParameter, id_DonViQuanLyParameter, trang_ThaiParameter);
        }
    
        public virtual int sua_vanbang(Nullable<int> id_VanBang, string so_Hieu_Van_Bang, string ma_SV, string ho_Va_Ten, Nullable<bool> gioi_Tinh, Nullable<System.DateTime> ngay_Sinh, string noi_Sinh, string nganh_Hoc, string khoa_Hoc, Nullable<System.DateTime> ngay_Cap, string xep_Loai_Tot_Nghiep)
        {
            var id_VanBangParameter = id_VanBang.HasValue ?
                new ObjectParameter("Id_VanBang", id_VanBang) :
                new ObjectParameter("Id_VanBang", typeof(int));
    
            var so_Hieu_Van_BangParameter = so_Hieu_Van_Bang != null ?
                new ObjectParameter("So_Hieu_Van_Bang", so_Hieu_Van_Bang) :
                new ObjectParameter("So_Hieu_Van_Bang", typeof(string));
    
            var ma_SVParameter = ma_SV != null ?
                new ObjectParameter("Ma_SV", ma_SV) :
                new ObjectParameter("Ma_SV", typeof(string));
    
            var ho_Va_TenParameter = ho_Va_Ten != null ?
                new ObjectParameter("Ho_Va_Ten", ho_Va_Ten) :
                new ObjectParameter("Ho_Va_Ten", typeof(string));
    
            var gioi_TinhParameter = gioi_Tinh.HasValue ?
                new ObjectParameter("Gioi_Tinh", gioi_Tinh) :
                new ObjectParameter("Gioi_Tinh", typeof(bool));
    
            var ngay_SinhParameter = ngay_Sinh.HasValue ?
                new ObjectParameter("Ngay_Sinh", ngay_Sinh) :
                new ObjectParameter("Ngay_Sinh", typeof(System.DateTime));
    
            var noi_SinhParameter = noi_Sinh != null ?
                new ObjectParameter("Noi_Sinh", noi_Sinh) :
                new ObjectParameter("Noi_Sinh", typeof(string));
    
            var nganh_HocParameter = nganh_Hoc != null ?
                new ObjectParameter("Nganh_Hoc", nganh_Hoc) :
                new ObjectParameter("Nganh_Hoc", typeof(string));
    
            var khoa_HocParameter = khoa_Hoc != null ?
                new ObjectParameter("Khoa_Hoc", khoa_Hoc) :
                new ObjectParameter("Khoa_Hoc", typeof(string));
    
            var ngay_CapParameter = ngay_Cap.HasValue ?
                new ObjectParameter("Ngay_Cap", ngay_Cap) :
                new ObjectParameter("Ngay_Cap", typeof(System.DateTime));
    
            var xep_Loai_Tot_NghiepParameter = xep_Loai_Tot_Nghiep != null ?
                new ObjectParameter("Xep_Loai_Tot_Nghiep", xep_Loai_Tot_Nghiep) :
                new ObjectParameter("Xep_Loai_Tot_Nghiep", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_vanbang", id_VanBangParameter, so_Hieu_Van_BangParameter, ma_SVParameter, ho_Va_TenParameter, gioi_TinhParameter, ngay_SinhParameter, noi_SinhParameter, nganh_HocParameter, khoa_HocParameter, ngay_CapParameter, xep_Loai_Tot_NghiepParameter);
        }
    
        public virtual int sua_xeploai(Nullable<int> id_XepLoai, string ma_XepLoai, string ten_XepLoai, Nullable<decimal> diem_Toi_Thieu, Nullable<decimal> diem_Toi_Da, Nullable<bool> trang_Thai_Su_Dung)
        {
            var id_XepLoaiParameter = id_XepLoai.HasValue ?
                new ObjectParameter("Id_XepLoai", id_XepLoai) :
                new ObjectParameter("Id_XepLoai", typeof(int));
    
            var ma_XepLoaiParameter = ma_XepLoai != null ?
                new ObjectParameter("Ma_XepLoai", ma_XepLoai) :
                new ObjectParameter("Ma_XepLoai", typeof(string));
    
            var ten_XepLoaiParameter = ten_XepLoai != null ?
                new ObjectParameter("Ten_XepLoai", ten_XepLoai) :
                new ObjectParameter("Ten_XepLoai", typeof(string));
    
            var diem_Toi_ThieuParameter = diem_Toi_Thieu.HasValue ?
                new ObjectParameter("Diem_Toi_Thieu", diem_Toi_Thieu) :
                new ObjectParameter("Diem_Toi_Thieu", typeof(decimal));
    
            var diem_Toi_DaParameter = diem_Toi_Da.HasValue ?
                new ObjectParameter("Diem_Toi_Da", diem_Toi_Da) :
                new ObjectParameter("Diem_Toi_Da", typeof(decimal));
    
            var trang_Thai_Su_DungParameter = trang_Thai_Su_Dung.HasValue ?
                new ObjectParameter("Trang_Thai_Su_Dung", trang_Thai_Su_Dung) :
                new ObjectParameter("Trang_Thai_Su_Dung", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_xeploai", id_XepLoaiParameter, ma_XepLoaiParameter, ten_XepLoaiParameter, diem_Toi_ThieuParameter, diem_Toi_DaParameter, trang_Thai_Su_DungParameter);
        }
    
        public virtual int them_chuyennganh(string ma_ChuyenNganh, string ten_ChuyenNganh, Nullable<int> id_NganhHoc, Nullable<bool> trang_Thai_Su_Dung)
        {
            var ma_ChuyenNganhParameter = ma_ChuyenNganh != null ?
                new ObjectParameter("Ma_ChuyenNganh", ma_ChuyenNganh) :
                new ObjectParameter("Ma_ChuyenNganh", typeof(string));
    
            var ten_ChuyenNganhParameter = ten_ChuyenNganh != null ?
                new ObjectParameter("Ten_ChuyenNganh", ten_ChuyenNganh) :
                new ObjectParameter("Ten_ChuyenNganh", typeof(string));
    
            var id_NganhHocParameter = id_NganhHoc.HasValue ?
                new ObjectParameter("Id_NganhHoc", id_NganhHoc) :
                new ObjectParameter("Id_NganhHoc", typeof(int));
    
            var trang_Thai_Su_DungParameter = trang_Thai_Su_Dung.HasValue ?
                new ObjectParameter("Trang_Thai_Su_Dung", trang_Thai_Su_Dung) :
                new ObjectParameter("Trang_Thai_Su_Dung", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_chuyennganh", ma_ChuyenNganhParameter, ten_ChuyenNganhParameter, id_NganhHocParameter, trang_Thai_Su_DungParameter);
        }
    
        public virtual int them_donviquanly(string ma_DonViQuanLy, string ten_DonViQuanLy, string ten_DonViQuanLy_Cha, Nullable<bool> trang_Thai_Su_Dung)
        {
            var ma_DonViQuanLyParameter = ma_DonViQuanLy != null ?
                new ObjectParameter("Ma_DonViQuanLy", ma_DonViQuanLy) :
                new ObjectParameter("Ma_DonViQuanLy", typeof(string));
    
            var ten_DonViQuanLyParameter = ten_DonViQuanLy != null ?
                new ObjectParameter("Ten_DonViQuanLy", ten_DonViQuanLy) :
                new ObjectParameter("Ten_DonViQuanLy", typeof(string));
    
            var ten_DonViQuanLy_ChaParameter = ten_DonViQuanLy_Cha != null ?
                new ObjectParameter("Ten_DonViQuanLy_Cha", ten_DonViQuanLy_Cha) :
                new ObjectParameter("Ten_DonViQuanLy_Cha", typeof(string));
    
            var trang_Thai_Su_DungParameter = trang_Thai_Su_Dung.HasValue ?
                new ObjectParameter("Trang_Thai_Su_Dung", trang_Thai_Su_Dung) :
                new ObjectParameter("Trang_Thai_Su_Dung", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_donviquanly", ma_DonViQuanLyParameter, ten_DonViQuanLyParameter, ten_DonViQuanLy_ChaParameter, trang_Thai_Su_DungParameter);
        }
    
        public virtual int them_dot_cap(string ten_Van_Bang, string ten_Dot_Cap)
        {
            var ten_Van_BangParameter = ten_Van_Bang != null ?
                new ObjectParameter("Ten_Van_Bang", ten_Van_Bang) :
                new ObjectParameter("Ten_Van_Bang", typeof(string));
    
            var ten_Dot_CapParameter = ten_Dot_Cap != null ?
                new ObjectParameter("Ten_Dot_Cap", ten_Dot_Cap) :
                new ObjectParameter("Ten_Dot_Cap", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_dot_cap", ten_Van_BangParameter, ten_Dot_CapParameter);
        }
    
        public virtual int them_khoahoc(string ma_KhoaHoc, Nullable<int> nam_Bat_Dau, Nullable<int> nam_Ket_Thuc, Nullable<bool> trang_Thai)
        {
            var ma_KhoaHocParameter = ma_KhoaHoc != null ?
                new ObjectParameter("Ma_KhoaHoc", ma_KhoaHoc) :
                new ObjectParameter("Ma_KhoaHoc", typeof(string));
    
            var nam_Bat_DauParameter = nam_Bat_Dau.HasValue ?
                new ObjectParameter("Nam_Bat_Dau", nam_Bat_Dau) :
                new ObjectParameter("Nam_Bat_Dau", typeof(int));
    
            var nam_Ket_ThucParameter = nam_Ket_Thuc.HasValue ?
                new ObjectParameter("Nam_Ket_Thuc", nam_Ket_Thuc) :
                new ObjectParameter("Nam_Ket_Thuc", typeof(int));
    
            var trang_ThaiParameter = trang_Thai.HasValue ?
                new ObjectParameter("Trang_Thai", trang_Thai) :
                new ObjectParameter("Trang_Thai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_khoahoc", ma_KhoaHocParameter, nam_Bat_DauParameter, nam_Ket_ThucParameter, trang_ThaiParameter);
        }
    
        public virtual int them_nganhhoc(string ma_NganhHoc, string ten_Nganh, Nullable<bool> trang_Thai_Su_Dung)
        {
            var ma_NganhHocParameter = ma_NganhHoc != null ?
                new ObjectParameter("Ma_NganhHoc", ma_NganhHoc) :
                new ObjectParameter("Ma_NganhHoc", typeof(string));
    
            var ten_NganhParameter = ten_Nganh != null ?
                new ObjectParameter("Ten_Nganh", ten_Nganh) :
                new ObjectParameter("Ten_Nganh", typeof(string));
    
            var trang_Thai_Su_DungParameter = trang_Thai_Su_Dung.HasValue ?
                new ObjectParameter("Trang_Thai_Su_Dung", trang_Thai_Su_Dung) :
                new ObjectParameter("Trang_Thai_Su_Dung", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_nganhhoc", ma_NganhHocParameter, ten_NganhParameter, trang_Thai_Su_DungParameter);
        }
    
        public virtual int them_nguoidung(string ma_NguoiDung, string ten_Dang_Nhap, string mat_Khau, string loai_NguoiDung)
        {
            var ma_NguoiDungParameter = ma_NguoiDung != null ?
                new ObjectParameter("Ma_NguoiDung", ma_NguoiDung) :
                new ObjectParameter("Ma_NguoiDung", typeof(string));
    
            var ten_Dang_NhapParameter = ten_Dang_Nhap != null ?
                new ObjectParameter("Ten_Dang_Nhap", ten_Dang_Nhap) :
                new ObjectParameter("Ten_Dang_Nhap", typeof(string));
    
            var mat_KhauParameter = mat_Khau != null ?
                new ObjectParameter("Mat_Khau", mat_Khau) :
                new ObjectParameter("Mat_Khau", typeof(string));
    
            var loai_NguoiDungParameter = loai_NguoiDung != null ?
                new ObjectParameter("Loai_NguoiDung", loai_NguoiDung) :
                new ObjectParameter("Loai_NguoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_nguoidung", ma_NguoiDungParameter, ten_Dang_NhapParameter, mat_KhauParameter, loai_NguoiDungParameter);
        }
    
        public virtual int them_sinhvien(string ma_SinhVien, string ho_Va_Ten, Nullable<bool> gioi_Tinh, Nullable<System.DateTime> ngay_Sinh, Nullable<int> id_ChuyenNganh, Nullable<int> id_KhoaHoc, string so_Dien_Thoai, string email, Nullable<decimal> diem_Trung_Binh_Tich_Luy, Nullable<int> id_XepLoai, Nullable<int> id_DonViQuanLy, Nullable<bool> trang_Thai)
        {
            var ma_SinhVienParameter = ma_SinhVien != null ?
                new ObjectParameter("Ma_SinhVien", ma_SinhVien) :
                new ObjectParameter("Ma_SinhVien", typeof(string));
    
            var ho_Va_TenParameter = ho_Va_Ten != null ?
                new ObjectParameter("Ho_Va_Ten", ho_Va_Ten) :
                new ObjectParameter("Ho_Va_Ten", typeof(string));
    
            var gioi_TinhParameter = gioi_Tinh.HasValue ?
                new ObjectParameter("Gioi_Tinh", gioi_Tinh) :
                new ObjectParameter("Gioi_Tinh", typeof(bool));
    
            var ngay_SinhParameter = ngay_Sinh.HasValue ?
                new ObjectParameter("Ngay_Sinh", ngay_Sinh) :
                new ObjectParameter("Ngay_Sinh", typeof(System.DateTime));
    
            var id_ChuyenNganhParameter = id_ChuyenNganh.HasValue ?
                new ObjectParameter("Id_ChuyenNganh", id_ChuyenNganh) :
                new ObjectParameter("Id_ChuyenNganh", typeof(int));
    
            var id_KhoaHocParameter = id_KhoaHoc.HasValue ?
                new ObjectParameter("Id_KhoaHoc", id_KhoaHoc) :
                new ObjectParameter("Id_KhoaHoc", typeof(int));
    
            var so_Dien_ThoaiParameter = so_Dien_Thoai != null ?
                new ObjectParameter("So_Dien_Thoai", so_Dien_Thoai) :
                new ObjectParameter("So_Dien_Thoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var diem_Trung_Binh_Tich_LuyParameter = diem_Trung_Binh_Tich_Luy.HasValue ?
                new ObjectParameter("Diem_Trung_Binh_Tich_Luy", diem_Trung_Binh_Tich_Luy) :
                new ObjectParameter("Diem_Trung_Binh_Tich_Luy", typeof(decimal));
    
            var id_XepLoaiParameter = id_XepLoai.HasValue ?
                new ObjectParameter("Id_XepLoai", id_XepLoai) :
                new ObjectParameter("Id_XepLoai", typeof(int));
    
            var id_DonViQuanLyParameter = id_DonViQuanLy.HasValue ?
                new ObjectParameter("Id_DonViQuanLy", id_DonViQuanLy) :
                new ObjectParameter("Id_DonViQuanLy", typeof(int));
    
            var trang_ThaiParameter = trang_Thai.HasValue ?
                new ObjectParameter("Trang_Thai", trang_Thai) :
                new ObjectParameter("Trang_Thai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_sinhvien", ma_SinhVienParameter, ho_Va_TenParameter, gioi_TinhParameter, ngay_SinhParameter, id_ChuyenNganhParameter, id_KhoaHocParameter, so_Dien_ThoaiParameter, emailParameter, diem_Trung_Binh_Tich_LuyParameter, id_XepLoaiParameter, id_DonViQuanLyParameter, trang_ThaiParameter);
        }
    
        public virtual int them_vanbang(string so_Hieu_Van_Bang, string ma_SV, string ho_Va_Ten, Nullable<bool> gioi_Tinh, Nullable<System.DateTime> ngay_Sinh, string noi_Sinh, string nganh_Hoc, string khoa_Hoc, Nullable<System.DateTime> ngay_Cap, string xep_Loai_Tot_Nghiep)
        {
            var so_Hieu_Van_BangParameter = so_Hieu_Van_Bang != null ?
                new ObjectParameter("So_Hieu_Van_Bang", so_Hieu_Van_Bang) :
                new ObjectParameter("So_Hieu_Van_Bang", typeof(string));
    
            var ma_SVParameter = ma_SV != null ?
                new ObjectParameter("Ma_SV", ma_SV) :
                new ObjectParameter("Ma_SV", typeof(string));
    
            var ho_Va_TenParameter = ho_Va_Ten != null ?
                new ObjectParameter("Ho_Va_Ten", ho_Va_Ten) :
                new ObjectParameter("Ho_Va_Ten", typeof(string));
    
            var gioi_TinhParameter = gioi_Tinh.HasValue ?
                new ObjectParameter("Gioi_Tinh", gioi_Tinh) :
                new ObjectParameter("Gioi_Tinh", typeof(bool));
    
            var ngay_SinhParameter = ngay_Sinh.HasValue ?
                new ObjectParameter("Ngay_Sinh", ngay_Sinh) :
                new ObjectParameter("Ngay_Sinh", typeof(System.DateTime));
    
            var noi_SinhParameter = noi_Sinh != null ?
                new ObjectParameter("Noi_Sinh", noi_Sinh) :
                new ObjectParameter("Noi_Sinh", typeof(string));
    
            var nganh_HocParameter = nganh_Hoc != null ?
                new ObjectParameter("Nganh_Hoc", nganh_Hoc) :
                new ObjectParameter("Nganh_Hoc", typeof(string));
    
            var khoa_HocParameter = khoa_Hoc != null ?
                new ObjectParameter("Khoa_Hoc", khoa_Hoc) :
                new ObjectParameter("Khoa_Hoc", typeof(string));
    
            var ngay_CapParameter = ngay_Cap.HasValue ?
                new ObjectParameter("Ngay_Cap", ngay_Cap) :
                new ObjectParameter("Ngay_Cap", typeof(System.DateTime));
    
            var xep_Loai_Tot_NghiepParameter = xep_Loai_Tot_Nghiep != null ?
                new ObjectParameter("Xep_Loai_Tot_Nghiep", xep_Loai_Tot_Nghiep) :
                new ObjectParameter("Xep_Loai_Tot_Nghiep", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_vanbang", so_Hieu_Van_BangParameter, ma_SVParameter, ho_Va_TenParameter, gioi_TinhParameter, ngay_SinhParameter, noi_SinhParameter, nganh_HocParameter, khoa_HocParameter, ngay_CapParameter, xep_Loai_Tot_NghiepParameter);
        }
    
        public virtual int them_xeploai(string ma_XepLoai, string ten_XepLoai, Nullable<decimal> diem_Toi_Thieu, Nullable<decimal> diem_Toi_Da, Nullable<bool> trang_Thai_Su_Dung)
        {
            var ma_XepLoaiParameter = ma_XepLoai != null ?
                new ObjectParameter("Ma_XepLoai", ma_XepLoai) :
                new ObjectParameter("Ma_XepLoai", typeof(string));
    
            var ten_XepLoaiParameter = ten_XepLoai != null ?
                new ObjectParameter("Ten_XepLoai", ten_XepLoai) :
                new ObjectParameter("Ten_XepLoai", typeof(string));
    
            var diem_Toi_ThieuParameter = diem_Toi_Thieu.HasValue ?
                new ObjectParameter("Diem_Toi_Thieu", diem_Toi_Thieu) :
                new ObjectParameter("Diem_Toi_Thieu", typeof(decimal));
    
            var diem_Toi_DaParameter = diem_Toi_Da.HasValue ?
                new ObjectParameter("Diem_Toi_Da", diem_Toi_Da) :
                new ObjectParameter("Diem_Toi_Da", typeof(decimal));
    
            var trang_Thai_Su_DungParameter = trang_Thai_Su_Dung.HasValue ?
                new ObjectParameter("Trang_Thai_Su_Dung", trang_Thai_Su_Dung) :
                new ObjectParameter("Trang_Thai_Su_Dung", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_xeploai", ma_XepLoaiParameter, ten_XepLoaiParameter, diem_Toi_ThieuParameter, diem_Toi_DaParameter, trang_Thai_Su_DungParameter);
        }
    
        public virtual int xoa_chuyennganh(Nullable<int> id_ChuyenNganh)
        {
            var id_ChuyenNganhParameter = id_ChuyenNganh.HasValue ?
                new ObjectParameter("Id_ChuyenNganh", id_ChuyenNganh) :
                new ObjectParameter("Id_ChuyenNganh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_chuyennganh", id_ChuyenNganhParameter);
        }
    
        public virtual int xoa_donviquanly(Nullable<int> id_DonViQuanLy)
        {
            var id_DonViQuanLyParameter = id_DonViQuanLy.HasValue ?
                new ObjectParameter("Id_DonViQuanLy", id_DonViQuanLy) :
                new ObjectParameter("Id_DonViQuanLy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_donviquanly", id_DonViQuanLyParameter);
        }
    
        public virtual int xoa_dot_cap(Nullable<int> id_Dot_Cap)
        {
            var id_Dot_CapParameter = id_Dot_Cap.HasValue ?
                new ObjectParameter("Id_Dot_Cap", id_Dot_Cap) :
                new ObjectParameter("Id_Dot_Cap", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_dot_cap", id_Dot_CapParameter);
        }
    
        public virtual int xoa_khoahoc(Nullable<int> id_KhoaHoc)
        {
            var id_KhoaHocParameter = id_KhoaHoc.HasValue ?
                new ObjectParameter("Id_KhoaHoc", id_KhoaHoc) :
                new ObjectParameter("Id_KhoaHoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_khoahoc", id_KhoaHocParameter);
        }
    
        public virtual int xoa_nganhhoc(Nullable<int> id_NganhHoc)
        {
            var id_NganhHocParameter = id_NganhHoc.HasValue ?
                new ObjectParameter("Id_NganhHoc", id_NganhHoc) :
                new ObjectParameter("Id_NganhHoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_nganhhoc", id_NganhHocParameter);
        }
    
        public virtual int xoa_nguoidung(Nullable<int> id_NguoiDung)
        {
            var id_NguoiDungParameter = id_NguoiDung.HasValue ?
                new ObjectParameter("Id_NguoiDung", id_NguoiDung) :
                new ObjectParameter("Id_NguoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_nguoidung", id_NguoiDungParameter);
        }
    
        public virtual int xoa_sinhvien(Nullable<int> id_SinhVien)
        {
            var id_SinhVienParameter = id_SinhVien.HasValue ?
                new ObjectParameter("Id_SinhVien", id_SinhVien) :
                new ObjectParameter("Id_SinhVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_sinhvien", id_SinhVienParameter);
        }
    
        public virtual int xoa_vanbang(Nullable<int> id_VanBang)
        {
            var id_VanBangParameter = id_VanBang.HasValue ?
                new ObjectParameter("Id_VanBang", id_VanBang) :
                new ObjectParameter("Id_VanBang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_vanbang", id_VanBangParameter);
        }
    
        public virtual int xoa_xeploai(Nullable<int> id_XepLoai)
        {
            var id_XepLoaiParameter = id_XepLoai.HasValue ?
                new ObjectParameter("Id_XepLoai", id_XepLoai) :
                new ObjectParameter("Id_XepLoai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_xeploai", id_XepLoaiParameter);
        }
    
        public virtual ObjectResult<chon_sinhvien_Result> chon_sinhvien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<chon_sinhvien_Result>("chon_sinhvien");
        }
    
        public virtual ObjectResult<chon_vanbang_Result> chon_vanbang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<chon_vanbang_Result>("chon_vanbang");
        }
    }
}
