//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanBangTotNghiep_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanBangTam
    {
        public int Id_VanBang { get; set; }
        public string So_Hieu_Van_Bang { get; set; }
        public int Id_DotCap { get; set; }
        public int Id_SinhVien { get; set; }
        public System.DateTime Ngay_Cap { get; set; }
        public string Noi_Cap { get; set; }
        public int Trang_Thai { get; set; }
    
        public virtual dm_SinhVien dm_SinhVien { get; set; }
        public virtual DotCapBangTN DotCapBangTN { get; set; }
    }
}
